import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#07060E] overflow-x-hidden max-w-full'>
        <div className='bg-lightGreen text-center py-[15px] px-[30px] md:py-[8px] text-[14px] md:text-[18px]'>
          <p>Obtenez une réduction de 10% sur votre pré-commande</p>
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
