import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#07060E]'>
        <div className='bg-lightGreen text-center py-[15px] px-[30px] text-[14px] md:text-[20px]'>
          <p>Obtenez une réduction de 10% sur votre pré-commande <span className='ml-2'>&gt;</span></p>
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
